###################################################################################################
#                        Welcome to the Marlin Project's source of truth!                         #
#                                                                                                 #
# Why are we doing this?:                                                                         #
#   As our project grows, it gets hard to keep track of the values on everyone's subsystems as    #
#   they get more and more complicated. Consolidating all of our important design parameters,     #
#   inputs and outputs in the same file helps reduce miscommunications and ensures everyone is in #
#   the same page.                                                                                #
# What the hell is a YAML?:                                                                       #
#   YAML is a type of files that allows people to write data in a way that is readable to both a  #
#   person AND a computer. As opposed to other filetypes like JSON and XML, the syntax is pretty  #
#   nice and readable and will thus make a good reference for programmers and non-programmers in  #
#   the team.                                                                                     #
# (video explaining how to use a YAML) https://www.youtube.com/watch?v=BEki_rsWu4E                #
#                                                                                                 #
# Basic rules:                                                                                    #
#   1. Be clear with naming, limit acronym usage on any parameters you add                        #
#   2. Write the units in a comment using parenthesis and maintain unit system consistency        #
#   3. Write your name next to any parameters you own, notify owners of inputs before             #
#      changing them                                                                              #
#   4. Do not change OUTPUTS manually, only code should do this!!!                                #
#   5. No slop, only throw a value here if it actually is useful information. EX: things like     #
#      shaft speed, design propellant temps... Not things like super specific shaft dimensions or #
#      random off-design conditions                                                               #
#   6. Check if the value is already there before adding it                                       #
#                                                                                                 #
# If you have any questions about how to use this document, reach out to Alejandro Diaz Contreras #
# adiazcon@purdue.edu                                                                             #
#                                                                                                 #
###################################################################################################


######################################
###### TURBOPUMP SYSTEMS DESIGN ######
######################################

# High level performance (INPUTS)

lox_inlet_design_pressure: 50 #(psi) Alejandro Diaz Contreras NOT FINALIZED, ASK BEFORE USING
lox_inlet_design_temperature: 162.27 #(R) Alejandro Diaz Contreras NOT FINALIZED, ASK BEFORE USING
lox_outlet_design_pressure: 1000 #(psi) Alejandro Diaz Contreras
lox_design_mdot: 15.4 #(lbm/s) Alejandro Diaz Contreras

kero_inlet_design_pressure: 50 #(psi) Alejandro Diaz Contreras NOT FINALIZED, ASK BEFORE USING
kero_outlet_design_pressure: 1000 #(psi) Alejandro Diaz Contreras
kero_inlet_design_temperature: 536.67 #(R) Alejandro Diaz Contreras NOT FINALIZED, ASK BEFORE USING
kero_design_mdot: 7.4 #(lbm/s) Alejandro Diaz Contreras


# Performance dispersion (INPUTS)

min_ambient_temperature: 491.67 #(R) Alejandro Diaz Contreras NOT FINALIZED, ASK BEFORE USING
max_ambient_temperature: 563.67 #(R) Alejandro Diaz Contreras NOT FINALIZED, ASK BEFORE USING

min_lox_tank_press: 14.7 #(psi) Alejandro Diaz Contreras NOT FINALIZED, ASK BEFORE USING
max_lox_tank_press: 14.7 #(psi) Alejandro Diaz Contreras NOT FINALIZED, ASK BEFORE USING

min_kero_tank_press: 75 #(psi) Alejandro Diaz Contreras NOT FINALIZED, ASK BEFORE USING
max_kero_tank_press: 75 #(psi) Alejandro Diaz Contreras NOT FINALIZED, ASK BEFORE USING


# High level systems (OUTPUTS)




########################
###### SUBSYSTEMS ######
########################

# Rotor (INPUTS)

shaft_speed: 50000 #(RPM) Alejandro Diaz Contreras
#rotor_moment_of_inertia: -------------------------------------------------- #(lbm*in^2) Daniel Bennet


# Rotor (OUTPUTS)

#lox_coolant_rate: --------------------------------------------------------- #(lb/s) James Nida
#fuel_coolant_rate: -------------------------------------------------------- #(lb/s) James Nida


# IPS (INPUTS)

#IPS_gap_width: ------------------------------------------------------------ #(in) Chris Suffredini


# Gas generator (INPUTS)

GG_chamber_design_pressure: 390 #(psi) Miles Cohen
GG_chamber_OF: 0.28 #(Unitless) Miles Cohen

# Stator (INPUTS)

S_design_exit_pressure: 30 #(psi) Amanjyoti Mridha
S_inlet_pressure: 350 #(psi) Amanjyoti Mridha
S_mass_flow_rate: 1.25 #(lbs/s) Amanjyoti Mridha
S_inlet_temperature: 876.05 #(K) Amanjyoti Mridha
S_inlet_specific_heat: 1.1201 #(unitless) Amanjyoti Mridha
S_inlet_gas_constant: 8.3145 #(J/mol-K) Amanjyoti Mridha
S_inlet_molar_mass: 11.328 #(g/mol) Amanjyoti Mridha
S_number_nozzles: 8 #(unitless) Amanjyoti Mridha

# Turbine (INPUTS)

T_design_power_output: 180 #(HP) Amanjyoti Mridha
T_design_rpm: 50000 #(RPM) Amanjyoti Mridha
T_rotor_radius: 2 #(in) Amanjyoti Mridha
T_blade_height: 5 #(mm) Amanjyoti Mridha
T_blade_solidity: (1/0.8) #(unitless) Amanjyoti Mridha
T_degree_of_reaction: 0 #(unitless) Amanjyoti Mridha comments: pure impulse turbine
T_num_blades: 40 #(unitless) Amanjyoti Mridha
T_chord: 1 #(cm) Amanjyoti Mridha


T_dynamic_viscosity: 5.5522e-5 #(Pa-s) Amanjyoti Mridha
T_c_p: ((10.8660+11.6259+12.9042)/3 * 0.238845896632776) #(Btu/(lb*degF)) Amanjyoti Mridha

# Turbine (OUTPUTS)

#turbine_efficiency: ------------------------------------------------------- #(Unitless) Amanjyoti Mridha

##############################
###### UNIT CONVERSIONS ######
##############################

lbm_to_kg: 0.45359237 #(kg/lbm) 
hp_to_watt: 745.7 #(W/HP) 
rpm_to_rad_per_sec: (2*3.141592653589793/60) #(rad/s)/(RPM) 
cm_to_m: 0.01 #(m/cm) 
mm_to_m: 0.001 #(m/mm)
bar_to_pa: 100000 #(Pa/bar)
psi_to_pa: 6894.75729 #(Pa/psi)
in_to_cm: 2.54 #(cm/in)
in_to_m: 0.0254 #(m/in)
kw_to_hp: 1.34102209 #(hp/kw)
lbft_to_nm: 1.3558179483 #(Nm/lbft)
